// supabase/functions/generate-financial-statements/index.ts v1.0
// LOOP-FIN-002 — PDF Audit Package
// Builds a 7-page A4 PDF: Cover + 4 IFRS Statements + Notes + Trial Balance
// Input:  { tenant_id, financial_year, period_label, tenant_name, status,
//           signed_by?, signed_at?, income, balance_sheet, cash_flow, equity }
// Output: { success, url, expires_at, path, pages }
// Tech:   Deno + npm:pdf-lib (StandardFonts — no font files required)
// Storage: uploads to "financial-statements" bucket, returns 7-day signed URL

import { createClient } from "jsr:@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const JSON_H = { ...CORS, "Content-Type": "application/json" };

// ── Formatters ────────────────────────────────────────────────────────────────

function fmtR(n: unknown): string {
  const v = parseFloat(String(n)) || 0;
  const abs = Math.abs(v);
  const s = `R${abs.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  return v < 0 ? `(${s})` : s;
}

function fmtRNeg(n: unknown): string {
  const v = parseFloat(String(n)) || 0;
  const abs = Math.abs(v);
  return `R${abs.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function safe(n: unknown): number {
  return parseFloat(String(n)) || 0;
}

function fmtDate(d: string | Date): string {
  return new Date(d).toLocaleDateString("en-ZA", { day: "numeric", month: "long", year: "numeric" });
}

// ── Colours ───────────────────────────────────────────────────────────────────

const C = {
  darkGreen: rgb(0.102, 0.239, 0.169),
  midGreen:  rgb(0.176, 0.416, 0.310),
  white:     rgb(1, 1, 1),
  ink900:    rgb(0.051, 0.051, 0.051),
  ink700:    rgb(0.2, 0.2, 0.2),
  ink500:    rgb(0.45, 0.45, 0.45),
  ink300:    rgb(0.7, 0.7, 0.7),
  border:    rgb(0.89, 0.89, 0.89),
  bg:        rgb(0.957, 0.953, 0.945),
  success:   rgb(0.09, 0.56, 0.35),
  danger:    rgb(0.80, 0.15, 0.15),
  sectionBg: rgb(0.91, 0.93, 0.89),
  hlGreen:   rgb(0.88, 0.97, 0.91),
  hlRed:     rgb(0.97, 0.88, 0.88),
};

// ── Page constants ─────────────────────────────────────────────────────────────

const PW = 595.28;
const PH = 841.89;
const ML = 48;
const MR = 48;
const CW = PW - ML - MR;

// ── PDF Drawing Helpers ────────────────────────────────────────────────────────

// deno-lint-ignore no-explicit-any
type APage = any;
// deno-lint-ignore no-explicit-any
type AFont = any;

function dt(page: APage, text: string, x: number, y: number, sz: number, font: AFont, color = C.ink700) {
  if (y < 30) return;
  page.drawText(String(text ?? ""), { x, y, size: sz, font, color });
}

function dtr(page: APage, text: string, rx: number, y: number, sz: number, font: AFont, color = C.ink700) {
  const w = font.widthOfTextAtSize(String(text ?? ""), sz);
  dt(page, text, rx - w, y, sz, font, color);
}

function hr(page: APage, y: number, x1 = ML, x2 = PW - MR, color = C.border, th = 0.5) {
  page.drawLine({ start: { x: x1, y }, end: { x: x2, y }, thickness: th, color });
}

function rect(page: APage, x: number, y: number, w: number, h: number, color: ReturnType<typeof rgb>) {
  page.drawRectangle({ x, y, width: w, height: h, color });
}

function footer(page: APage, n: number, freg: AFont) {
  dt(page, `Generated by NuAi  ·  ${fmtDate(new Date())}  ·  Confidential`, ML, 24, 7, freg, C.ink300);
  dtr(page, String(n), PW - MR, 24, 8, freg, C.ink300);
}

function stmtHeader(
  page: APage, tName: string, subtitle: string, r1: string, r2: string,
  stmtNum: string, freg: AFont, fbold: AFont
): number {
  const H = 76;
  rect(page, 0, PH - H, PW, H, C.darkGreen);
  dt(page, stmtNum, ML, PH - 17, 7.5, freg, rgb(0.65, 0.78, 0.70));
  const ns = tName.length > 30 ? 14 : 18;
  dt(page, tName, ML, PH - 40, ns, fbold, C.white);
  dt(page, subtitle, ML, PH - 59, 10, freg, rgb(0.80, 0.90, 0.84));
  dtr(page, r1, PW - MR, PH - 40, 8.5, freg, rgb(0.65, 0.78, 0.70));
  dtr(page, r2, PW - MR, PH - 55, 8.5, freg, rgb(0.65, 0.78, 0.70));
  return PH - H - 10;
}

function colHdr(page: APage, y: number, freg: AFont, fbold: AFont): number {
  dt(page, "Note", ML, y, 7.5, fbold, C.ink500);
  dtr(page, "Current Period (ZAR)", PW - MR - 80, y, 7.5, fbold, C.ink500);
  dtr(page, "Prior Period (ZAR)", PW - MR, y, 7.5, fbold, C.ink500);
  y -= 5;
  hr(page, y, ML, PW - MR, C.midGreen, 1.5);
  return y - 11;
}

type S = { y: number };

function secBar(page: APage, s: S, label: string, fbold: AFont) {
  rect(page, ML, s.y - 2, CW, 13, C.sectionBg);
  dt(page, label, ML + 4, s.y, 7.5, fbold, C.ink500);
  s.y -= 12;
}

interface RowOpts {
  bold?: boolean; shade?: boolean; negative?: boolean;
  sub?: string; indent?: number; green?: boolean;
}

function row(page: APage, s: S, label: string, value: number | null, opts: RowOpts = {}, freg: AFont, fbold: AFont) {
  const { bold = false, shade = false, negative = false, sub, indent = 0, green = false } = opts;
  const rh = sub ? 26 : 18;
  if (shade) rect(page, ML, s.y - 4, CW, rh, C.bg);
  const f = bold ? fbold : freg;
  const sz = bold ? 10 : 9;
  dt(page, label, ML + 4 + indent * 12, s.y, sz, f, C.ink700);
  if (sub) dt(page, sub, ML + 4 + indent * 12, s.y - 13, 7, freg, C.ink500);
  if (value !== null) {
    const neg = negative || value < 0;
    const str = neg ? `(${fmtRNeg(Math.abs(value))})` : fmtR(value);
    const col = bold
      ? (green || value >= 0 && !negative ? C.midGreen : C.danger)
      : C.ink700;
    dtr(page, str, PW - MR - 80, s.y, sz, f, col);
    dtr(page, "—", PW - MR, s.y, 8.5, freg, C.ink300);
  }
  s.y -= sub ? 20 : 14;
}

function netRow(page: APage, s: S, label: string, value: number, pct: number, freg: AFont, fbold: AFont) {
  const bg = value >= 0 ? C.hlGreen : C.hlRed;
  rect(page, ML, s.y - 4, CW, 26, bg);
  hr(page, s.y + 21, ML, PW - MR, value >= 0 ? rgb(0, 0.65, 0.4) : C.danger, 1.5);
  dt(page, label, ML + 4, s.y, 10.5, fbold, C.ink900);
  dt(page, `Net margin: ${safe(pct).toFixed(1)}%`, ML + 4, s.y - 13, 7.5, freg, C.ink500);
  dtr(page, fmtR(value), PW - MR - 80, s.y, 10.5, fbold, value >= 0 ? C.success : C.danger);
  dtr(page, "—", PW - MR, s.y, 8.5, freg, C.ink300);
  s.y -= 26;
}

function stmtClose(page: APage, freg: AFont) {
  // Anchors the bottom of each statement page — makes blank space feel intentional
  hr(page, 82, ML, PW - MR, C.midGreen, 0.8);
  dt(page, "NuAi Financial Reporting Suite  |  IFRS for SMEs  |  All figures in South African Rand (ZAR)", ML, 70, 6.5, freg, C.ink300);
}

function noteBox(page: APage, s: S, text: string, freg: AFont) {
  const words = text.split(" ");
  const lines: string[] = [];
  let cur = "";
  const maxW = CW - 16;
  for (const w of words) {
    const test = cur ? `${cur} ${w}` : w;
    if (freg.widthOfTextAtSize(test, 8) > maxW && cur) { lines.push(cur); cur = w; }
    else { cur = test; }
  }
  if (cur) lines.push(cur);
  const bh = lines.length * 12 + 14;
  rect(page, ML, s.y - bh + 10, CW, bh, C.bg);
  page.drawLine({ start: { x: ML, y: s.y - bh + 10 }, end: { x: ML, y: s.y + 10 }, thickness: 2, color: C.midGreen });
  let ly = s.y;
  for (const l of lines) { dt(page, l, ML + 8, ly, 7.5, freg, C.ink500); ly -= 12; }
  s.y = ly - 6;
}

// ── Main Deno handler ─────────────────────────────────────────────────────────

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });

  try {
    const body = await req.json();
    const {
      tenant_id, financial_year, period_label, tenant_name,
      status, signed_by, signed_at,
      income: inc, balance_sheet: bs, cash_flow: cf, equity: eq,
    } = body;

    if (!tenant_id) throw new Error("tenant_id required");
    if (!inc || !bs || !cf || !eq) throw new Error("All 4 statement data objects required (income, balance_sheet, cash_flow, equity)");

    const db = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    const [tcRes, jlRes, coaRes] = await Promise.all([
      db.from("tenant_config")
        .select("company_registration_number,vat_number,vat_registered,financial_year_end")
        .eq("tenant_id", tenant_id)
        .maybeSingle(),
      db.from("journal_lines")
        .select("account_code,account_name,debit_amount,credit_amount")
        .eq("tenant_id", tenant_id),
      db.from("chart_of_accounts")
        .select("account_code,account_name,account_type")
        .eq("tenant_id", tenant_id)
        .order("account_code"),
    ]);

    const tc = (tcRes.data ?? {}) as Record<string, unknown>;
    const jLines = (jlRes.data ?? []) as { account_code: string; account_name: string; debit_amount: unknown; credit_amount: unknown }[];
    const coa = (coaRes.data ?? []) as { account_code: string; account_name: string; account_type: string }[];

    const tbMap: Record<string, { code: string; name: string; dr: number; cr: number }> = {};
    for (const a of coa) {
      tbMap[a.account_code] = { code: a.account_code, name: a.account_name, dr: 0, cr: 0 };
    }
    for (const l of jLines) {
      if (!tbMap[l.account_code]) {
        tbMap[l.account_code] = { code: l.account_code, name: l.account_name || l.account_code, dr: 0, cr: 0 };
      }
      tbMap[l.account_code].dr += safe(l.debit_amount);
      tbMap[l.account_code].cr += safe(l.credit_amount);
    }
    const tb = Object.values(tbMap)
      .filter((r) => r.dr > 0.005 || r.cr > 0.005)
      .sort((a, b) => a.code.localeCompare(b.code));

    const doc = await PDFDocument.create();
    doc.setTitle(`${String(tenant_name)} — ${String(financial_year)} IFRS Financial Statements`);
    doc.setAuthor("NuAi Financial Reporting");
    doc.setSubject("IFRS for SMEs Financial Statements");
    doc.setCreationDate(new Date());

    const freg  = await doc.embedFont(StandardFonts.Helvetica);
    const fbold = await doc.embedFont(StandardFonts.HelveticaBold);

    // ── PAGE 1: COVER ─────────────────────────────────────────────────────────
    const p1 = doc.addPage([PW, PH]);

    rect(p1, 0, PH - 210, PW, 210, C.darkGreen);
    dt(p1, "NuAi  ·  Financial Reporting", ML, PH - 26, 7.5, freg, rgb(0.6, 0.73, 0.66));
    const ns = String(tenant_name).length > 32 ? 18 : 24;
    dt(p1, String(tenant_name), ML, PH - 68, ns, fbold, C.white);
    dt(p1, "IFRS Financial Statements", ML, PH - 96, 13, freg, rgb(0.80, 0.90, 0.84));
    dt(p1, String(period_label), ML, PH - 116, 9, freg, rgb(0.65, 0.78, 0.70));
    dt(p1, `Prepared ${fmtDate(new Date())}`, ML, PH - 135, 8, freg, rgb(0.55, 0.68, 0.62));
    dt(p1, "Functional currency: ZAR  ·  IFRS for SMEs compliant", ML, PH - 152, 8, freg, rgb(0.55, 0.68, 0.62));

    const sMap: Record<string, string> = { draft: "DRAFT", reviewed: "REVIEWED", signed: "AUDITOR SIGNED OFF", locked: "LOCKED" };
    const sBgMap: Record<string, ReturnType<typeof rgb>> = {
      draft: rgb(0.60, 0.50, 0), reviewed: rgb(0, 0.47, 0.65),
      signed: rgb(0.09, 0.56, 0.35), locked: rgb(0.45, 0.45, 0.45),
    };
    const sLabel = sMap[String(status)] ?? "DRAFT";
    const sBg = sBgMap[String(status)] ?? rgb(0.45, 0.45, 0.45);
    const slw = fbold.widthOfTextAtSize(sLabel, 7.5) + 16;
    rect(p1, PW - MR - slw, PH - 110, slw, 17, sBg);
    dt(p1, sLabel, PW - MR - slw + 8, PH - 105, 7.5, fbold, C.white);
    dt(p1, String(financial_year), PW - MR - fbold.widthOfTextAtSize(String(financial_year), 9), PH - 133, 9, fbold, rgb(0.65, 0.78, 0.70));

    let y1 = PH - 240;
    dt(p1, "Table of Contents", ML, y1, 13, fbold, C.ink900);
    y1 -= 8;
    hr(p1, y1, ML, PW - MR, C.midGreen, 1.5);
    y1 -= 18;

    const toc = [
      ["1.", "Statement of Comprehensive Income", "2"],
      ["2.", "Statement of Financial Position", "3"],
      ["3.", "Statement of Cash Flows", "4"],
      ["4.", "Statement of Changes in Equity", "5"],
      ["5.", "Notes to the Financial Statements", "6"],
      ["6.", "Trial Balance", "7"],
    ];
    for (const [n, l, pg] of toc) {
      dt(p1, n, ML, y1, 10, freg, C.ink500);
      dt(p1, l, ML + 18, y1, 10, freg, C.ink700);
      dtr(p1, pg, PW - MR, y1, 10, freg, C.ink500);
      y1 -= 18;
    }

    y1 -= 14;
    hr(p1, y1, ML, PW - MR, C.border);
    y1 -= 20;

    dt(p1, "Entity Details", ML, y1, 11, fbold, C.ink900);
    y1 -= 18;

    const fyEnd = (() => {
      const fe = String(tc.financial_year_end ?? "");
      if (fe) {
        const [mm] = fe.split("-");
        const months = ["", "January", "February", "March", "April", "May", "June",
          "July", "August", "September", "October", "November", "December"];
        return `31 ${months[parseInt(mm)] ?? "December"}`;
      }
      return "31 December";
    })();

    const entityRows: [string, string][] = [
      ["Entity name:", String(tenant_name)],
      ["Registration number:", String(tc.company_registration_number ?? "See entity records")],
      ["VAT number:", String(tc.vat_number ?? (tc.vat_registered ? "Registered" : "Not registered"))],
      ["Financial year end:", fyEnd],
      ["Accounting framework:", "IFRS for SMEs"],
      ["Measurement basis:", "Historical cost"],
      ["Reporting period:", String(period_label)],
    ];
    for (const [lbl, val] of entityRows) {
      dt(p1, lbl, ML, y1, 9, freg, C.ink500);
      dt(p1, val, ML + 155, y1, 9, freg, C.ink700);
      y1 -= 15;
    }

    if (signed_by) {
      y1 -= 8;
      hr(p1, y1, ML, PW - MR, C.border);
      y1 -= 18;
      dt(p1, "Auditor / Reviewer", ML, y1, 11, fbold, C.ink900);
      y1 -= 16;
      dt(p1, "Signed by:", ML, y1, 9, freg, C.ink500);
      dt(p1, String(signed_by), ML + 155, y1, 9, fbold, C.midGreen);
      if (signed_at) {
        y1 -= 15;
        dt(p1, "Sign-off date:", ML, y1, 9, freg, C.ink500);
        dt(p1, fmtDate(signed_at), ML + 155, y1, 9, freg, C.ink700);
      }
    }
    footer(p1, 1, freg);

    // ── PAGE 2: INCOME STATEMENT ───────────────────────────────────────────────
    const p2 = doc.addPage([PW, PH]);
    const s2: S = { y: stmtHeader(p2, String(tenant_name), "Statement of Comprehensive Income", String(period_label), String(financial_year), "Statement 1 of 4", freg, fbold) - 4 };
    s2.y = colHdr(p2, s2.y, freg, fbold);

    secBar(p2, s2, "REVENUE", fbold);
    row(p2, s2, "Revenue from contracts with customers", safe(inc.revenue), { indent: 1 }, freg, fbold);
    row(p2, s2, "Total Revenue", safe(inc.revenue), { bold: true, shade: true, green: true }, freg, fbold);
    s2.y -= 4;

    secBar(p2, s2, "COST OF SALES", fbold);
    row(p2, s2, "Cost of inventories recognised as expense", safe(inc.cogs), { indent: 1, negative: true }, freg, fbold);
    row(p2, s2, "Gross Profit", safe(inc.grossProfit), { bold: true, shade: true, green: true, sub: `Gross margin: ${safe(inc.grossMarginPct).toFixed(1)}%` }, freg, fbold);
    s2.y -= 4;

    secBar(p2, s2, "OPERATING EXPENSES", fbold);
    for (const line of ((inc.opexLines ?? []) as { label: string; amount: number }[])) {
      row(p2, s2, line.label, safe(line.amount), { indent: 1, negative: true }, freg, fbold);
    }
    if (safe(inc.depreciationTotal) > 0) {
      row(p2, s2, "Depreciation of property, plant and equipment", safe(inc.depreciationTotal), { indent: 1, negative: true }, freg, fbold);
    }
    row(p2, s2, "Total Operating Expenses", safe(inc.totalOpex) + safe(inc.depreciationTotal), { bold: true, shade: true, negative: true }, freg, fbold);
    s2.y -= 4;

    netRow(p2, s2, safe(inc.netProfit) >= 0 ? "Profit for the Period" : "Loss for the Period", safe(inc.netProfit), safe(inc.netMarginPct), freg, fbold);
    s2.y -= 6;

    noteBox(p2, s2, "Prepared in accordance with IFRS for SMEs. Functional currency: South African Rand (ZAR). Historical cost basis. COGS derived from weighted average cost (AVCO). Comparative figures will populate after prior year-end close.", freg);
    stmtClose(p2, freg);
    footer(p2, 2, freg);

    // ── PAGE 3: BALANCE SHEET ──────────────────────────────────────────────────
    const p3 = doc.addPage([PW, PH]);
    const s3: S = { y: stmtHeader(p3, String(tenant_name), "Statement of Financial Position", `As at ${fmtDate(new Date())}`, String(financial_year), "Statement 2 of 4", freg, fbold) - 4 };
    s3.y = colHdr(p3, s3.y, freg, fbold);

    const balanced = Boolean(bs.balanced);
    rect(p3, ML, s3.y - 4, CW, 17, balanced ? C.hlGreen : C.hlRed);
    dt(p3, balanced ? "Assets = Liabilities + Equity  [BALANCED]" : "Statement does not balance  [REVIEW REQUIRED]", ML + 4, s3.y, 9, fbold, balanced ? C.success : C.danger);
    s3.y -= 22;

    const totalCA = safe(bs.inventoryValue) + safe(bs.cashAtBank) + safe(bs.receivables) + safe(bs.vatReceivable);
    const totalAssets = totalCA + safe(bs.fixedAssetsNBV);
    const totalLiab = safe(bs.payables) + safe(bs.vatLiability) + safe(bs.opexAccruals);
    const totalEq = safe(bs.totalEquity);

    secBar(p3, s3, "ASSETS \u2014 CURRENT ASSETS", fbold);
    row(p3, s3, "Inventories (at weighted average cost)", safe(bs.inventoryValue), { indent: 1 }, freg, fbold);
    if (safe(bs.cashAtBank) > 0) row(p3, s3, "Cash and cash equivalents", safe(bs.cashAtBank), { indent: 1 }, freg, fbold);
    row(p3, s3, "Trade and other receivables", safe(bs.receivables), { indent: 1 }, freg, fbold);
    if (safe(bs.vatReceivable) > 0) row(p3, s3, "VAT receivable \u2014 SARS", safe(bs.vatReceivable), { indent: 1 }, freg, fbold);
    row(p3, s3, "Total Current Assets", totalCA, { bold: true, shade: true, green: true }, freg, fbold);
    s3.y -= 4;

    secBar(p3, s3, "ASSETS \u2014 NON-CURRENT ASSETS", fbold);
    if (safe(bs.fixedAssetsCost) > 0) {
      row(p3, s3, "Property, plant and equipment \u2014 cost", safe(bs.fixedAssetsCost), { indent: 1 }, freg, fbold);
      row(p3, s3, "Accumulated depreciation", safe(bs.fixedAssetsAccDep), { indent: 1, negative: true }, freg, fbold);
      row(p3, s3, "Net book value", safe(bs.fixedAssetsNBV), { bold: true, shade: true, green: true }, freg, fbold);
    } else {
      row(p3, s3, "Property, plant and equipment", 0, { indent: 1 }, freg, fbold);
    }
    row(p3, s3, "TOTAL ASSETS", totalAssets, { bold: true, shade: true, green: true }, freg, fbold);
    s3.y -= 6;
    hr(p3, s3.y, ML, PW - MR, C.midGreen, 1.5);
    s3.y -= 14;

    secBar(p3, s3, "LIABILITIES \u2014 CURRENT LIABILITIES", fbold);
    row(p3, s3, "Trade and other payables", safe(bs.payables), { indent: 1 }, freg, fbold);
    if (safe(bs.vatLiability) > 0) row(p3, s3, "VAT payable \u2014 SARS", safe(bs.vatLiability), { indent: 1 }, freg, fbold);
    if (safe(bs.opexAccruals) > 0) row(p3, s3, "Accrued operating expenses", safe(bs.opexAccruals), { indent: 1 }, freg, fbold);
    row(p3, s3, "Total Liabilities", totalLiab, { bold: true, shade: true }, freg, fbold);
    s3.y -= 4;

    secBar(p3, s3, "EQUITY", fbold);
    row(p3, s3, "Share capital", safe(bs.shareCapital), { indent: 1 }, freg, fbold);
    row(p3, s3, "Retained earnings \u2014 opening", safe(bs.openingRetained), { indent: 1 }, freg, fbold);
    row(p3, s3, safe(bs.currentYearPL) >= 0 ? "Profit for the year" : "Loss for the year", Math.abs(safe(bs.currentYearPL)), { indent: 1, negative: safe(bs.currentYearPL) < 0 }, freg, fbold);
    row(p3, s3, "Total Equity", totalEq, { bold: true, shade: true, green: true }, freg, fbold);
    s3.y -= 4;
    row(p3, s3, "TOTAL LIABILITIES + EQUITY", totalLiab + totalEq, { bold: true, shade: true, green: true }, freg, fbold);
    s3.y -= 8;

    noteBox(p3, s3, "Inventories at AVCO (IAS 2). Fixed assets at cost less accumulated depreciation — straight-line method (IAS 16). Trade payables represent open purchase orders. Equity sourced from equity_ledger configuration.", freg);
    stmtClose(p3, freg);
    footer(p3, 3, freg);

    // ── PAGE 4: CASH FLOW ──────────────────────────────────────────────────────
    const p4 = doc.addPage([PW, PH]);
    const s4: S = { y: stmtHeader(p4, String(tenant_name), "Statement of Cash Flows", String(period_label), String(financial_year), "Statement 3 of 4", freg, fbold) - 4 };
    s4.y = colHdr(p4, s4.y, freg, fbold);

    secBar(p4, s4, "OPERATING ACTIVITIES (Simplified Indirect Method)", fbold);
    row(p4, s4, "Net profit / (loss) for the period", safe(cf.netProfit), { indent: 1 }, freg, fbold);
    row(p4, s4, "Add: depreciation of PPE (non-cash)", safe(cf.depreciationTotal), { indent: 2 }, freg, fbold);
    row(p4, s4, "Net cash from operating activities", safe(cf.netOperating), { bold: true, shade: true, green: true, sub: "Profit + depreciation add-back (simplified)" }, freg, fbold);
    s4.y -= 4;

    secBar(p4, s4, "INVESTING ACTIVITIES", fbold);
    row(p4, s4, "Purchase of property, plant and equipment", safe(cf.capexPaid ?? 0), { indent: 1, negative: true }, freg, fbold);
    row(p4, s4, "Net cash used in investing activities", safe(cf.netInvesting ?? -safe(cf.capexPaid)), { bold: true, shade: true }, freg, fbold);
    s4.y -= 4;

    secBar(p4, s4, "FINANCING ACTIVITIES", fbold);
    row(p4, s4, "Capital contributions / owner injections", safe(cf.financingInflow ?? 0), { indent: 1 }, freg, fbold);
    row(p4, s4, "Loan repayments / owner drawings", safe(cf.financingOutflow ?? 0), { indent: 1, negative: true }, freg, fbold);
    row(p4, s4, "Net cash from financing activities", safe(cf.netFinancing ?? 0), { bold: true, shade: true }, freg, fbold);
    s4.y -= 6;

    const nc = safe(cf.netCash);
    rect(p4, ML, s4.y - 4, CW, 26, nc >= 0 ? C.hlGreen : C.hlRed);
    hr(p4, s4.y + 21, ML, PW - MR, nc >= 0 ? rgb(0, 0.65, 0.4) : C.danger, 1.5);
    dt(p4, "Net increase / (decrease) in cash and cash equivalents", ML + 4, s4.y, 10, fbold, C.ink900);
    dtr(p4, fmtR(nc), PW - MR - 80, s4.y, 10, fbold, nc >= 0 ? C.success : C.danger);
    dtr(p4, "\u2014", PW - MR, s4.y, 8.5, freg, C.ink300);
    s4.y -= 32;

    noteBox(p4, s4, "Simplified indirect method: net profit adjusted for non-cash depreciation. Working capital movements require prior-period snapshots and are not included. Financing activities identified from bank statement keyword matching.", freg);
    stmtClose(p4, freg);
    footer(p4, 4, freg);

    // ── PAGE 5: CHANGES IN EQUITY ──────────────────────────────────────────────
    const p5 = doc.addPage([PW, PH]);
    let y5 = stmtHeader(p5, String(tenant_name), "Statement of Changes in Equity", String(period_label), String(financial_year), "Statement 4 of 4", freg, fbold) - 4;

    const cW1 = 200, cWn = 88;
    dt(p5, "Movement", ML + 4, y5, 7.5, fbold, C.ink500);
    dtr(p5, "Share Capital", ML + cW1 + cWn, y5, 7.5, fbold, C.ink500);
    dtr(p5, "Retained Earnings", ML + cW1 + cWn * 2, y5, 7.5, fbold, C.ink500);
    dtr(p5, "Total Equity", ML + cW1 + cWn * 3, y5, 7.5, fbold, C.ink500);
    y5 -= 5;
    hr(p5, y5, ML, PW - MR, C.midGreen, 1.5);
    y5 -= 14;

    const sc = safe(eq.shareCapital);
    const op = safe(eq.openingRetained);
    const cy = safe(eq.currentYearPL);
    const cl = op + cy;

    function eqRow(label: string, sc_: number | null, re: number | null, tot: number | null, bold = false, shade = false) {
      if (shade) rect(p5, ML, y5 - 4, ML + cW1 + cWn * 3 - ML, 20, C.bg);
      const f = bold ? fbold : freg;
      const sz = bold ? 10 : 9;
      dt(p5, label, ML + 4, y5, sz, f, C.ink700);
      const numCol = bold ? C.midGreen : C.ink700;
      if (sc_ !== null) dtr(p5, fmtR(sc_), ML + cW1 + cWn, y5, sz, f, numCol);
      if (re !== null) dtr(p5, re === 0 ? "\u2014" : fmtR(re), ML + cW1 + cWn * 2, y5, sz, f, bold ? (re >= 0 ? C.midGreen : C.danger) : (re >= 0 ? C.ink700 : C.danger));
      if (tot !== null) dtr(p5, fmtR(tot), ML + cW1 + cWn * 3, y5, sz, f, bold ? (tot >= 0 ? C.midGreen : C.danger) : C.ink700);
      y5 -= bold ? 22 : 18;
    }

    eqRow("Opening balance", sc, op, sc + op);
    eqRow(cy >= 0 ? "Net profit for the period" : "Net loss for the period", null, cy, cy);
    eqRow("Dividends declared", null, 0, 0);
    hr(p5, y5 + 4, ML, PW - MR, C.border, 0.5);
    eqRow("Closing balance", sc, cl, sc + cl, true, true);
    y5 -= 14;

    const s5: S = { y: y5 };
    noteBox(p5, s5, "Share capital and opening retained earnings sourced from financial setup (equity_ledger). Dividends declared: not recorded in current period. Future periods will show year-on-year retained earnings movement after year-end close.", freg);
    stmtClose(p5, freg);
    footer(p5, 5, freg);

    // ── PAGE 6: NOTES ──────────────────────────────────────────────────────────
    const p6 = doc.addPage([PW, PH]);
    rect(p6, 0, PH - 70, PW, 70, C.darkGreen);
    dt(p6, "Notes to the Financial Statements", ML, PH - 36, 15, fbold, C.white);
    dt(p6, `${String(tenant_name)}  \u00b7  ${String(financial_year)}  \u00b7  ${String(period_label)}`, ML, PH - 57, 8.5, freg, rgb(0.73, 0.84, 0.78));
    let y6 = PH - 88;

    const vatRegistered = Boolean(tc.vat_registered);
    const notes: { num: string; title: string; body: string }[] = [
      {
        num: "1", title: "Basis of Preparation",
        body: `These financial statements have been prepared in accordance with the International Financial Reporting Standard for Small and Medium-sized Entities (IFRS for SMEs). The functional and presentation currency is the South African Rand (ZAR). The statements have been prepared on the historical cost basis. The reporting period is ${String(period_label)}.`,
      },
      {
        num: "2", title: "Revenue",
        body: `Revenue is measured at the fair value of consideration received or receivable. Revenue from the sale of goods is recognised when the performance obligation is satisfied at the point of sale. Revenue for the period: ${fmtR(safe(inc.revenue))} (prior period: not available). Gross margin: ${safe(inc.grossMarginPct).toFixed(1)}%. Net margin: ${safe(inc.netMarginPct).toFixed(1)}%.`,
      },
      {
        num: "3", title: "Inventories",
        body: `Inventories are measured at the lower of cost and net realisable value. Cost is determined using the weighted average cost method (AVCO), recalculated automatically on each stock movement. Inventory carrying value at period end: ${fmtR(safe(bs.inventoryValue))}.`,
      },
      {
        num: "4", title: "Property, Plant and Equipment",
        body: `PPE is stated at cost less accumulated depreciation (IAS 16). The straight-line depreciation method is applied over each asset's useful economic life. Assets are reviewed for impairment annually. Gross carrying amount: ${fmtR(safe(bs.fixedAssetsCost))}. Accumulated depreciation: ${fmtR(safe(bs.fixedAssetsAccDep))}. Net book value: ${fmtR(safe(bs.fixedAssetsNBV))}.`,
      },
      {
        num: "5", title: "Value Added Tax",
        body: vatRegistered
          ? `The entity is registered for Value Added Tax at the standard rate of 15% (VAT number: ${String(tc.vat_number ?? "registered")}). Output VAT arises on taxable supplies. Input VAT is claimed on qualifying business expenses. ${safe(bs.vatLiability) > 0 ? `Net VAT liability payable to SARS: ${fmtR(safe(bs.vatLiability))}.` : safe(bs.vatReceivable) > 0 ? `Net VAT receivable from SARS: ${fmtR(safe(bs.vatReceivable))}.` : "VAT position is neutral for the period."}`
          : "The entity is not registered for Value Added Tax. All amounts in these statements are stated inclusive of any applicable taxes.",
      },
    ];

    for (const note of notes) {
      dt(p6, `Note ${note.num}: ${note.title}`, ML, y6, 11, fbold, C.ink900);
      y6 -= 4;
      hr(p6, y6, ML, PW - MR, C.midGreen, 1);
      y6 -= 14;

      const words = note.body.split(" ");
      let line = "";
      const maxW = CW - 8;
      for (const w of words) {
        const test = line ? `${line} ${w}` : w;
        if (freg.widthOfTextAtSize(test, 8.5) > maxW && line) {
          dt(p6, line, ML + 4, y6, 8.5, freg, C.ink700);
          y6 -= 13;
          line = w;
        } else {
          line = test;
        }
      }
      if (line) { dt(p6, line, ML + 4, y6, 8.5, freg, C.ink700); y6 -= 13; }
      y6 -= 14;
    }
    footer(p6, 6, freg);

    // ── PAGE 7: TRIAL BALANCE ──────────────────────────────────────────────────
    const p7 = doc.addPage([PW, PH]);
    rect(p7, 0, PH - 70, PW, 70, C.darkGreen);
    dt(p7, "Trial Balance", ML, PH - 36, 15, fbold, C.white);
    dt(p7, `${String(tenant_name)}  \u00b7  ${String(financial_year)}  \u00b7  All posted journals`, ML, PH - 57, 8.5, freg, rgb(0.73, 0.84, 0.78));
    let y7 = PH - 90;

    const tcodeW = 55, tnameW = 250, tdrW = 90, tcrW = 90;
    const tdrX = ML + tcodeW + tnameW;
    const tcrX = tdrX + tdrW;

    rect(p7, ML, y7 - 2, CW, 15, C.sectionBg);
    dt(p7, "Account Code", ML + 2, y7, 7.5, fbold, C.ink500);
    dt(p7, "Account Name", ML + tcodeW + 2, y7, 7.5, fbold, C.ink500);
    dtr(p7, "Debit (ZAR)", tdrX + tdrW, y7, 7.5, fbold, C.ink500);
    dtr(p7, "Credit (ZAR)", tcrX + tcrW, y7, 7.5, fbold, C.ink500);
    y7 -= 5;
    hr(p7, y7, ML, PW - MR, C.midGreen, 1.5);
    y7 -= 13;

    let tbDr = 0, tbCr = 0;
    if (tb.length === 0) {
      dt(p7, "No journal entries posted for this period.", ML + 4, y7, 9, freg, C.ink500);
      y7 -= 18;
    } else {
      for (let i = 0; i < tb.length; i++) {
        if (y7 < 60) break;
        const r = tb[i];
        if (i % 2 === 0) rect(p7, ML, y7 - 3, CW, 13, rgb(0.975, 0.975, 0.972));
        dt(p7, r.code, ML + 2, y7, 7.5, freg, C.ink500);
        const nm = r.name.length > 38 ? r.name.substring(0, 37) + "\u2026" : r.name;
        dt(p7, nm, ML + tcodeW + 2, y7, 7.5, freg, C.ink700);
        if (r.dr > 0.005) dtr(p7, fmtR(r.dr), tdrX + tdrW, y7, 7.5, freg, C.ink700);
        if (r.cr > 0.005) dtr(p7, fmtR(r.cr), tcrX + tcrW, y7, 7.5, freg, C.ink700);
        tbDr += r.dr; tbCr += r.cr;
        y7 -= 13;
      }

      y7 -= 4;
      hr(p7, y7, ML, PW - MR, C.midGreen, 1.5);
      y7 -= 13;
      rect(p7, ML, y7 - 4, CW, 20, C.bg);
      dt(p7, "TOTALS", ML + 2, y7, 9, fbold, C.ink900);
      dtr(p7, fmtR(tbDr), tdrX + tdrW, y7, 9, fbold, C.ink900);
      dtr(p7, fmtR(tbCr), tcrX + tcrW, y7, 9, fbold, C.ink900);
      y7 -= 24;

      const tbOk = Math.abs(tbDr - tbCr) < 1;
      rect(p7, ML, y7 - 4, CW, 16, tbOk ? C.hlGreen : C.hlRed);
      dt(p7, tbOk ? "Trial balance is balanced  [Dr = Cr]" : `Out of balance by ${fmtR(Math.abs(tbDr - tbCr))}  [REVIEW REQUIRED]`, ML + 4, y7, 9, fbold, tbOk ? C.success : C.danger);
    }
    footer(p7, 7, freg);

    // ── Upload to Storage + return signed URL ──────────────────────────────────
    const pdfBytes = await doc.save();
    const pdfPath = `${String(tenant_id)}/${String(financial_year)}-${Date.now()}.pdf`;
    // Wrap Uint8Array in Blob — Supabase Storage client in Deno requires Blob
    // for correct multipart encoding. Raw Uint8Array causes a silent 500.
    const pdfBlob = new Blob([pdfBytes], { type: "application/pdf" });

    const { error: upErr } = await db.storage
      .from("financial-statements")
      .upload(pdfPath, pdfBlob, { contentType: "application/pdf", upsert: true });
    if (upErr) throw new Error(`Storage upload failed: ${upErr.message}`);

    const { data: urlData, error: urlErr } = await db.storage
      .from("financial-statements")
      .createSignedUrl(pdfPath, 60 * 60 * 24 * 7);
    if (urlErr || !urlData?.signedUrl) throw new Error(`Signed URL failed: ${urlErr?.message ?? "no URL returned"}`);

    return new Response(JSON.stringify({
      success: true,
      url: urlData.signedUrl,
      expires_at: new Date(Date.now() + 604800000).toISOString(),
      path: pdfPath,
      pages: 7,
    }), { headers: JSON_H });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[generate-financial-statements]", msg);
    return new Response(JSON.stringify({ success: false, error: msg }), { status: 500, headers: JSON_H });
  }
});
